### ISSUE TITLE
How to use website

### ISSUE THREAD

**Issue by NitroGhost** [DenisGorbachev/priest#2]
your website gives no indication on how to use it. if I upload a file, it downloads the same file, if I paste code, nothing happens.

**Comment by Ranunculus** [comment]
Hello, @NitroGhost .

Thank you for your comment!

The interface itself is straight forward: you paste a piece of JS, HTML or CSS code and in the area below (which shows automatically) you get allocated converted CoffeeScript, Jade or Style code. It’s working right now, so maybe it’s just a browser view didn’t allowed you to see a text area below, could it be it?

As for batch (folder) conversion, I’m afraid it only works for JS, HTML and CSS to newer languages, so if you try to convert CoffeeScript to JS, it will give you the same CoffeeScript file. 

Hope, this helps!
